FROM golang:1.22.0-bookworm AS builder
COPY install.sh /root/eth_bootstrap/
RUN apt-get update && apt-get install -y jq
RUN cd /root/eth_bootstrap && ./install.sh

FROM debian:bookworm-slim
COPY --from=builder /root/eth_bootstrap/eth_bin /root/eth_bootstrap/default.genesis.json /root/eth_bootstrap/config.yml /root/eth_bootstrap/scripts/

WORKDIR /root/eth_bootstrap